version: '3.8'

services:
  bot:
    build: .
    #restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src:rw
      - ./logs:/app/logs:rw
    networks:
      - bot-network
    environment:
      - PYTHONUNBUFFERED=1

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-clockinbot}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data: